spring:
  application:
    name: Spring App
  # Archivos de internacionalizacion
  messages:
    basename: messages
  # Base de datos en memoria
  h2:
    console:
      enabled: true

server:
  port: 2021

logging:
  level:
    root: INFO

# Habilitando endpoints de actuators
management:
  endpoints:
    web:
      exposure:
        include: "*"

# http://localhost:2021/swagger-ui/index.html
# http://localhost:2021/explorer/index.html#

